// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slmprqzzyhuvwillbwla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsbXBycXp6eWh1dndpbGxid2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NzA5MjEsImV4cCI6MjA2NDE0NjkyMX0.q_rrEiar2HFWXkiVqCTSv01SeBlPyMh0JqzwJSPegfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);